# Site settings
title: Willy Rodríguez
email: willyrv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Willy Rodriguez github site. Some tutorials related with population genetics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: willy_r_v
github_username:  willyrv

# Build settings
markdown: kramdown
